export const morseCodeMappings = {
    A: [true, false],
    B: [false, true, true, true],
    C: [false, true, false, true],
    D: [false, true, true],
    E: [true],
    F: [true, true, false, true],
    G: [false, false, true],
    H: [true, true, true, true],
    I: [true, true],
    J: [true, false, false, false],
    K: [false, true, false],
    L: [true, false, true, true],
    M: [false, false],
    N: [false, true],
    O: [false, false, false],
    P: [true, false, false, true],
    Q: [false, false, true, false],
    R: [true, false, true],
    S: [true, true, true],
    T: [false],
    U: [true, true, false],
    V: [true, true, true, false],
    W: [true, false, false],
    X: [false, true, true, false],
    Y: [false, true, false, false],
    Z: [false, false, true, true],
    1: [true, false, false, false, false],
    2: [true, true, false, false, false],
    3: [true, true, true, false, false],
    4: [true, true, true, true, false],
    5: [true, true, true, true, true],
    6: [false, true, true, true, true],
    7: [false, false, true, true, true],
    8: [false, false, false, true, true],
    9: [false, false, false, false, true],
    0: [false, false, false, false, false],
}